# Generated by Django 4.2.16 on 2024-10-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_en', models.CharField(max_length=355, verbose_name='Header (English)')),
                ('summary_en', models.CharField(max_length=5000, verbose_name='Summary (English)')),
                ('description_en', models.CharField(max_length=5000, verbose_name='Description (English)')),
                ('header_ar', models.CharField(max_length=355, verbose_name='Header (Arabic)')),
                ('summary_ar', models.CharField(max_length=5000, verbose_name='Summary (Arabic)')),
                ('description_ar', models.CharField(max_length=5000, verbose_name='Description (Arabic)')),
                ('photo', models.ImageField(upload_to='images/', verbose_name='Photo')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
                ('link_title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Title (English)')),
                ('link_title_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link Title (Arabic)')),
            ],
        ),
    ]
